sensors:
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, 1.14, 0.91]
      rpy: [0, 0, 'pi']
  break_beam_2:
    type: break_beam
    pose:
      xyz: [1.6, 2.41, 0.91]
      rpy: [0, 0, 'pi']
  proximity_sensor_1:
    type: proximity_sensor
    pose:
      xyz: [0.95, 2.6, 0.92]
      rpy: [0, 0, 0]
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [-0.678949, -1.162651, 1.042288]
      rpy: [1.566555, 0.799728, 0.007013]
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [-0.470056, -0.385053, 1.205591]
      rpy: [1.560394, 1.289001, 0]
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [-0.683764, 0.382626, 1.040872]
      rpy: [1.566644, 0.799727, 0.007013]
  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [1.204024, 2.210892, 1.466381]
      rpy: [0.202579, 1.5707, 0.002580]
  depth_camera_1:
    type: depth_camera
    pose:
      xyz: [-0.3, -0.383, 1.2]
      rpy: [0, 1.5707, 0]
  laser_profiler_1:
    type: laser_profiler
    pose:
      xyz: [1.21, 4, 1.6]
      rpy: ['-pi', 'pi/2', 'pi/2']
